### ISSUE TITLE
Possibility to generate an expirable token for flask server to Opal communication

### ISSUE THREAD

**Issue by IvoLeist** [obiba/opal-python-client#13]
Dear Opal developers,

its me again the one who is hoping to use Opal in a web application for biomedical research
as part of the 3TR project (https://3tr-imi.eu/).

If you are interested in our progress: 
https://github.com/IvoLeist/docker-opal/tree/postgres-keycloak
This should work right out of the box. 

Since the backend of our webapp is py3 based we have translated [core.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/core.py) and [rest.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/rest.py) to py3
*If you want I can add these files to my personal fork? 

However, we were not able to integrate it because we are lacking the possibility to generate a token for a user. 
I checked [user.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/user.py) and it looks like you can only generate a user with a password or certificate, right? 

What we are envision is the generation of a expirable token (similar to Keycloak).

Can you give us an idea if that is already supported by Opal so we would just need to add a method to [user.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/user.py)

If that is not the case I would be willing to give it a shot (and even contribute to your repo if it works out) 
However, my experience with Java is quite limited so could you maybe guide me a little through your code? 

Our idea would be to extract the `X-Opal-Auth` token we have found in the Opal Frontend. 
Do you think this a good idea or should I generate a new token? 

Best regards, 
Ivo

**Comment by ymarcon** [comment]
Would the [Personal Access Token](http://opaldoc.obiba.org/en/latest/web-user-guide/my-profile.html#personal-access-tokens) match your needs (except that it does not expire, but could be easy to implement such functionality)?

By the way if you intend to develop/adapt new/existing functionalities for the 3TR project, you would have several possibilities:

* contribute directly by submitting code changes pull-requests
* subcontract with [Epigeny](https://www.epigeny.io) (my consulting company)
* collaborate with the [EUCan-Connect](https://eucanconnect.com/) project (for which Epigeny is a partner)

**Comment by IvoLeist** [comment]
Dear @ymarcon,

thank you for your quick answer.
 
The personal access token could match our needs for the beginning but
we need the token generation to be triggred by sending a keycloak token. 
Do you think that is easy to be implemented as well?

Depending if we decide ourselves in the end to settle with Opal I guess we need to discuss this options.
But for now we would resort to contributing directly to Opal.

Thus, are you willing to guide us a little bit through the 
authentication flow so we can try to implement that missing functionality?

**Comment by ymarcon** [comment]
As Opal uses Keycloak as an OpenID Connect provider, I guess that you want to go with the OAuth2's "Authorization Code Grant Flow". So it is more a OAuth/Keycloak issue than an Opal one (except probably the Bearer token validation phase). It is quite complex to setup and requires user manual intervention (identification in Keycloak and access request approval). In addition to that Opal will not restrict the permissions according to the scopes in the token (the client app will have the same rights as the user).

Then I would recommend using the "Personal Access Token" feature: user login in Opal (through Keycloak), creates a PAT with limited permissions. The client app will use this token to create a session, and following requests will use the session id to authenticate: this session id is stored in a cookie (opalid) that will expire. It is simple to use and libcurl will handle this nicely.

**Comment by IvoLeist** [comment]
Dear @ymarcon 

yes we would like to go with the PAT feature.
However, we do not want to have the user to login Opal 
because some use cases do  not require to go to the OPAL UI.

Thus, we have to first expose the Token generation on the Opal API
and then trigger it with the opal-python-client.

I would be willing to try to implement it but I am kinda lost in your code base.

So far I found in [user.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/user.py) SubjectCredentialsDto()
Which I found then in the java code of Opal here:
[opal/opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/administration/users/edit/SubjectCredentialsDtos.java](https://github.com/obiba/opal/blob/acfd94eca713b403fb002443901f3d12755905e4/opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/administration/users/edit/SubjectCredentialsDtos.java)

But could you point me to the code where you are creating a token?

Best regards,
Ivo

**Comment by IvoLeist** [comment]
Dear @ymarcon,

thank you for explaining me how to generate a token. We managed to do it via curl:

```
curl -H "Content-Type: application/x-protobuf+json" -v http://localhost:8880/ws/system/subject-token/_current/tokens -d '{name: "curl_token", token: "insertTokenHere", useR: false, useDatashield: true}' --cookie "opalsid=takeItFromAnyXHRrequest"
```
Did we understand it correctly that we have to have a cookie for that in order to make that work?
So it only works if triggered by the user. Thus, it cannot be triggered by the admin to create the token for a selected user?

We envision something similar to [user.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/user.py)
where a password / user account seems to be sufficient to call [SubjectCredentialsResource.java](https://github.com/obiba/opal/blob/master/opal-core-ws/src/main/java/org/obiba/opal/web/system/subject/SubjectCredentialsResource.java)
to create a new user with a password. Instead of the password we want to create the personal access token for that user.

For this we would have to modify [SubjectTokenResource.java](https://github.com/obiba/opal/blob/acfd94eca713b403fb002443901f3d12755905e4/opal-core-ws/src/main/java/org/obiba/opal/web/system/subject/SubjectTokenResource.java), right?

However, we are puzzled how to integrate there the authentication you are using in user.py
Looking into the verbose output of user.py we found some token `X-Opal-Auth` 
Are you willing to explain us where this is generated and what its use is?

Best regards,
Ivo

**Comment by ymarcon** [comment]
Instead of curl, use the following opal python client command:

```
echo -n "{name: 'curl_token', token: 'insertTokenHere', useR: false, useDatashield: true}" | opal rest -u administrator -p password -m POST -ct application/json /system/subject-token/_current/tokens
```

Using the cookie to authenticate makes sense only when sending multiple requests in the same session. The header `Authorization: X-Opal-Auth <some-credentials-string-here>` is a classic authentication string (like the [Basic](https://en.wikipedia.org/wiki/Basic_access_authentication) one) where the provided credentials string is the base64 encoding of "<username>:<password>".

If you have the password of the user, you can create a token for him. If you don't... having a personal token allows you to operate on behalf of the user. It's something that would require the user consent I think.

**Comment by IvoLeist** [comment]
Thank you @ymarcon  for providing me the necessary opal python client command.
Installing the newest version of the client using `sudo apt-get install opal-python-client` it  worked right out of the box.

However, we are missing a way to directly send the payload from python.
Your pipe is based on in [rest.py](https://github.com/obiba/opal-python-client/blob/master/src/main/python/opal/rest.py) :
```
if args.content_type:
            request.content_type(args.content_type)
            print('Enter content:')
            request.content(sys.stdin.read())
```
right?

Since it is kinda bad practice to call shell inside python flask
we would have to add an extra command line argument for the payload, right?

For the ones who are interested how to get a cookie when using the opal-python-client
just query e.g the Opal version with the verbose flag.
In the response you will find the cookie.

```
opal system -v --opal http://localhost:8880 -u username -p password --version 2>&1 | grep -oP '(?<=opalsid=).*' | cut -f1 -d";"
```

Regarding the `X-Opal-Auth` 
Did I understood it correctly we could generate that by:
```python
credentials = base64.b64encode("username:password".encode("utf-8"))
```

and pass this to `opal rest` via `--header `
e.g. { "Authorization": "X-Opal-Auth " + credentials}

Thus, in `opal rest` we would not need to provide `-u username -p password` to generate the PAT
or even better would this enable us to query the data directly via `opal rest` w/o generating a PAT at all?
