### ISSUE TITLE
'dict' object has no attribute 'separator'

### ISSUE THREAD

**Issue by djuarezgf** [obiba/opal-python-client#25]
When I execute the following command:
**opal import-csv --opal http://localhost:8880 --user administrator --password XXXX --path /projects/test/patients.csv --separator \t  --destination test --tables patient --type Patient  --identifiers Patient-ID --json**

I get the following message:
**'dict' object has no attribute 'separator'**

**Comment by ymarcon** [comment]
What if you put \t between quotes? `... --separator "\t" ...`

**Comment by djuarezgf** [comment]
The same result :/

**Comment by djuarezgf** [comment]
I use the latest version of obiba-opal (5.0.1)

**Comment by ymarcon** [comment]
Fixed and released, please try 5.0.2, thanks for the report.

**Comment by djuarezgf** [comment]
Thank you very much. It works!
