### ISSUE TITLE
perm-project: Missing 1 required positional argument

### ISSUE THREAD

**Issue by djuarezgf** [obiba/opal-python-client#28]
I am following the instructions for adding permissions for a project: https://opaldoc.obiba.org/en/latest/python-user-guide/permission/perm-project.html . However, I get an error message:

opal perm-project --opal http://opal:8080/opal --user administrator --password XXXXX --type USER --subject administrator --permission administrate --project ccp-20230428-10_05 --add
_map_permission() missing 1 required positional argument: 'permissions'

It is exactly the same as in the instructions:
opal perm-project --opal https://opal-demo.obiba.org --user administrator --password password --type USER --subject demouser --permission administrate --project datashield --add

Am I missing something?

**Comment by ymarcon** [comment]
Please update and try with version 5.1.1

**Comment by djuarezgf** [comment]
It has worked! Thank you!
